# Pipeline to run Bazel tests post-merge onto master

# disable CI builds 
trigger: none

# pre-merge pipeline specified as a resource to act as the trigger for builds of this pipeline
resources: 
  pipelines:
  - pipeline: pre-merge-pipeline
    source: pre-merge-pipeline
    trigger:
      branches:
        include: 
        - master

stages:
- stage: Bazel_Tests
  displayName: Test
  jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:  
    - script: |
        echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install -y bazel
      displayName: 'install bazel'
    - script: |
        bazel version
      displayName: 'show bazel version'
    - script: |
        cd bazel-hello
        bazel test --test_tag_filters=-benchmark ... 
      displayName: 'run all non-benchmark tests'