# Pipeline to run Bazel tests post-merge onto master
 
# allow CI builds only on master branch by excluding all other branches.
# enforce batch run, which will test all changes at once. This should result in a single run per PR that is merged onto master.
# the single run will include all changes introduced by the PR, instead of testing them sequentially.
trigger: 
  batch: true 
  branches:
    include:
    - master 

pr: none

stages:
- stage: Bazel_Tests
  displayName: Test
  jobs:
  - job: Test
    pool:
      name: 'VMSSPool'
    steps:  
    - script: |
        bazel version
      displayName: 'show bazel version'
    - script: |
        bazel test --test_tag_filters=-benchmark ... 
      displayName: 'run all non-benchmark tests'
    - task: CopyFiles@2
      inputs:
        sourceFolder: 'bazel-out/k8-fastbuild/bin/absl'
        #contents: '**' 
        targetFolder: '$(Build.ArtifactStagingDirectory)'
        #cleanTargetFolder: false # Optional
        #overWrite: false # Optional
        #flattenFolders: false # Optional
        #preserveTimestamp: false # Optional
    - task: UniversalPackages@0
      displayName: Universal Publish
      inputs:
        command: publish
        publishDirectory: '$(Build.ArtifactStagingDirectory)'
        vstsFeedPublish: 'minerva-poc-github/testfeed'
        vstsFeedPackagePublish: 'my-first-package'
        versionOption: minor
        packagePublishDescription: 'Quick test'


