# pre-merge pipeline
# triggered on PR only

trigger: none

pr:
- master

stages:
- stage: Bazel_Build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: 'VMSSPool'

    steps: 
    - script: |
        bazel version
      displayName: 'show bazel version'

    - script: |
        cd bazel-hello
        bazel build --remote_cache=http://remotecache.eastus.cloudapp.azure.com:9090 ...
      displayName: 'bazel build' 