# won't trigger on branch/PR/merge 
trigger: none

pr: none

stages:
- stage: Bazel_Build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: 'VMSSPool'

    steps: 

    - script: |
        bazel version
      displayName: 'show bazel version'

    - script: |
        bazel clean --expunge
      displayName: 'bazel clean with expunge'

    - script: |
        bazel build ...
      displayName: 'bazel build' 
